FROM registry.fedoraproject.org/fedora-minimal:43

RUN microdnf install -y \
    golang \
    make \
    git \
    && microdnf clean all

RUN go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest

WORKDIR /src
